# Generated by Django 5.2.6 on 2025-10-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
