# Generated by Django 5.2.6 on 2025-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_cv_education_cv_email_cv_experience_cv_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('labels', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
