# Generated by Django 5.2.6 on 2025-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cv',
            name='potential_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cv',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
